name: GitHub Pull Request Fetcher

on:
  pull_request:
    branches: [main]

jobs:
  fetch-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the script
        run: python GitHubPullRequestFetcher.py ${{ github.event_path }}
